name: Python CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.13' }
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Cache UV dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-
      - name: Cache virtual environment
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
      - name: Install dependencies from lockfile
        run: uv sync --frozen
      - name: Cache mypy
        uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: mypy-${{ runner.os }}-${{ hashFiles('src/**', 'tests/**', 'pyproject.toml') }}
      - name: Cache ruff
        uses: actions/cache@v4
        with:
          path: .ruff_cache
          key: ruff-${{ runner.os }}-${{ hashFiles('src/**', 'tests/**', 'pyproject.toml') }}
      - name: Run linting, formatting, and type checks
        run: |
          uv run ruff check --cache-dir .ruff_cache .
          uv run ruff format --cache-dir .ruff_cache --check .
          uv run mypy src tests
      - name: Run tests with coverage
        run: uv run pytest --cov --cov-fail-under=85
